version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - D:\Projects\CloudReadyWorkshop\DockerVolumes\sqlserver:/var/opt/mssql/data
  mongodb:
    image : mongo
    container_name: mongodb
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - D:\Projects\CloudReadyWorkshop\DockerVolumes\mongo:/var/opt/mongo/data